*** Settings ***

Resource    ../../Resources/Utils/Android/A_Common.robot
Resource    ../../Resources/Utils/Android/A_LandingPage.robot
Resource    ../../Resources/Utils/Android/A_Insure.robot
Resource    ../../Resources/Utils/Android/A_Loans.robot
Resource    ../../Resources/Utils/Android/A_Remit.robot
Resource    ../../Resources/Utils/Android/A_Features/A_Goals/A_OwnAHome.robot
Resource    ../../Resources/Utils/Android/A_Features/A_SetAGoal.robot
Resource    ../../Resources/Utils/Android/A_Features/A_TradeSmart.robot
Resource    ../../Resources/Utils/Android/A_Features/A_FamilyAccount.robot
Resource    ../../Resources/Utils/Android/A_Features/A_ManageAccount.robot
Resource    ../../Resources/Utils/Android/A_Features/A_TaxHarvesting.robot
Resource    ../../Resources/Utils/Android/A_Features/A_SaveTaxes.robot
Resource    ../../Resources/Utils/Android/A_Features/A_Consolidate.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_InvestLandingPage.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_SaveSmart.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_GiltFunds.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_UltraShort.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_ELSSTaxSaver.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_USETF.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_EquityIndex.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_SectorFunds.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_ValueFunds.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_52WkHighIndia.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_52WkHighUS.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_BankPSUBonds.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_DigiGold.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_Crypto.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_FD.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_MutualFunds.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_Stocks.robot
Resource    ../../Resources/Utils/Android/A_Invest/A_USStocks.robot
Resource    ../../Resources/Utils/Android/A_Login.robot
Resource    ../../Resources/Utils/Android/A_Signup.robot
Resource    ../../Resources/Utils/Android/A_About.robot
Resource    ../../Resources/Utils/Android/A_Blog.robot