*** Settings ***

# Import Pages for Tests
Resource    ../../Resources/Utils/DesktopWeb/Common.robot
Resource    ../../Resources/Utils/DesktopWeb/LandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Login.robot
Resource    ../../Resources/Utils/DesktopWeb/Signup.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/InvestLandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SaveSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/GiltFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/DigitalGold.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/EquityIndex.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SectorFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/BankPSUBonds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/ELSSTaxSaver.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/Crypto.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/FD.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/USETF.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/ValueFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/52WkHighIndia.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/52WkHighUS.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/UltraShort.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/MutualFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/Stocks.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/USStocks.robot
Resource    ../../Resources/Utils/DesktopWeb/Loans.robot
Resource    ../../Resources/Utils/DesktopWeb/Insure.robot
Resource    ../../Resources/Utils/DesktopWeb/Remit.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/SetAGoal.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/OwnAHome.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/BuyACar.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/SaveTax.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/RetireEasy.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/EducateMyChild.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/ForeignVacation.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/25thAnniversary.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/CreateMyGoal.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/TradeSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/FamilyAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/ManageAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/TaxHarvesting.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/SaveTaxes.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Consolidate.robot
Resource    ../../Resources/Utils/DesktopWeb/Footer.robot
Resource    ../../Resources/Utils/DesktopWeb/FundHouse.robot
Resource    ../../Resources/Utils/DesktopWeb/CreateAccountForPostLogin.robot
Resource    ../../Resources/Utils/DesktopWeb/HealthInsurancePostLogin/KYC.robot
Resource    ../../Resources/Utils/DesktopWeb/HealthInsurancePostLogin/AddFamilyDetails.robot
Resource    ../../Resources/Utils/DesktopWeb/HealthInsurancePostLogin/HealthInsuranceLandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/UnauthenticatedLinks/LiquidFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/UnauthenticatedLinks/ForgotPassword.robot
Resource    ../../Resources/Utils/DesktopWeb/UnauthenticatedLinks/TaxCalculator.robot