*** Settings ***

Resource    ../../Resources/Utils/DesktopWeb/Common.robot
Resource    ../../Resources/Utils/DesktopWeb/LandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Login.robot
Resource    ../../Resources/Utils/DesktopWeb/Signup.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/InvestLandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SaveSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/GiltFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/DigitalGold.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/EquityIndex.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SectorFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Loans.robot
Resource    ../../Resources/Utils/DesktopWeb/Insure.robot
Resource    ../../Resources/Utils/DesktopWeb/Remit.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/SetAGoal.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/OwnAHome.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/BuyACar.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/SaveTax.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/RetireEasy.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/EducateMyChild.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/ForeignVacation.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/25thAnniversary.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/CreateMyGoal.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/TradeSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/FamilyAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/ManageAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/TaxHarvesting.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/SaveTaxes.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Consolidate.robot