*** Settings ***

Resource    ../../Resources/Utils/DesktopWeb/Common.robot
Resource    ../../Resources/Utils/DesktopWeb/LandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/InvestLandingPage.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/52WkHighIndia.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/52WkHighUS.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SaveSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/BankPSUBonds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/GiltFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/ELSSTaxSaver.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/DigitalGold.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/EquityIndex.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/SectorFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/ValueFunds.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/TopGainers.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/UltraShort.robot
Resource    ../../Resources/Utils/DesktopWeb/Invest/USETF.robot
Resource    ../../Resources/Utils/DesktopWeb/Loans.robot
Resource    ../../Resources/Utils/DesktopWeb/Insure.robot
Resource    ../../Resources/Utils/DesktopWeb/Remit.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_SetAGoal.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/OwnAHome.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/BuyACar.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Goals/SaveTax.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_TradeSmart.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_FamilyAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_ManageAccount.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_TaxHarvesting.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_SaveTaxes.robot
Resource    ../../Resources/Utils/DesktopWeb/Features/Features_Consolidate.robot